name: PR Validation (Husky Equivalent)

on:
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '18'

jobs:
  # Fast parallel validations
  quick-checks:
    name: Quick Validations
    runs-on: ubuntu-latest
    timeout-minutes: 8

    strategy:
      fail-fast: false
      matrix:
        check: [type-check, lint-and-format]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Type Check
        if: matrix.check == 'type-check'
        run: npm run type-check

      - name: Lint and Format Check
        if: matrix.check == 'lint-and-format'
        run: npm run check

  # Build and test (depends on quick checks)
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [quick-checks]
    timeout-minutes: 12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test
